{...}: {
  imports = [
    ./cli/aws-cli.nix
    ./cli/claude.nix
    ./cli/direnv.nix
    ./cli/docker.nix
    ./cli/gh.nix
    ./cli/git.nix
    ./cli/k8s.nix
    ./cli/monitoring.nix
    ./cli/networking.nix
    ./cli/systools.nix
    ./cli/tealdeer.nix
    ./cli/npm.nix
    ./cli/useful.nix
    ./cli/zsh.nix
    ./cli/rust.nix
    ./gui/alacritty.nix
    ./gui/chromium.nix
    ./gui/firefox.nix
    ./gui/sway.nix
    ./gui/waybar.nix
    ./gui/mako.nix
    ./gui/screenshotin.nix
    ./gui/rofi-launcher.nix
    ./gui/ghostty.nix
    ./gui/calibre.nix
    ./gui/steam.nix
  ];
}
